import React from 'react';
import Head from 'next/head';
import {Input} from '@nextui-org/react';

import {useGetUserQuery} from '../utils/testQuery';

export default () => {
	const {data} = useGetUserQuery();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
			</Head>
			<main>
				<h1>Hello, world!</h1>
				<p>Наконец-то настроил CI/CD</p>
				<Input/>
				<div>{JSON.stringify(data)}</div>
			</main>
		</>
	);
};
