import React from 'react';
import Head from 'next/head';

export default () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				<h1>Hello, world!</h1>
				<p>Наконец-то настроил CI/CD</p>
			</main>
		</>
	);
};
