on:
  workflow_call

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'
          cache: 'npm'

      - name: yarn install, build, and test
        run: |
          npm install yarn
          yarn --frozen-lockfile
          yarn build
          yarn test