name: PR Checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    name: Build & Test
    uses: gigachads-mirea/Gigachads-Frontend/.github/workflows/build-and-test.yml@master
