name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-test:
    name: Build & Test
    uses: gigachads-mirea/Gigachads-Frontend/.github/workflows/build-and-test.yml@master

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-20.04
    needs: [ build-and-test ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker auth -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-20.04
    needs: [ docker ]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
